-- ============================================================================
-- 0012 — Fine-grained permission catalogue (RBAC expansion)
-- ============================================================================
-- Generated: expands the permission catalogue to a full resource x action
-- matrix (363 slugs) across every product domain, and grants sensible
-- subsets to the built-in roles (admin gets everything). Two new staff roles
-- (editor, analyst) are added so the catalogue is immediately useful.

-- new staff roles
INSERT INTO roles (slug, name, description, is_system) VALUES
  ('editor',  'Catalogue Editor', 'Manage the anime catalogue and streaming sources', true),
  ('analyst', 'Analyst',          'Read and export platform analytics', true)
ON CONFLICT (slug) DO NOTHING;

-- permission catalogue
INSERT INTO permissions (slug, "group", description) VALUES
  ('anime.view', 'catalogue', 'View anime'),
  ('anime.create', 'catalogue', 'Create anime'),
  ('anime.edit', 'catalogue', 'Edit anime'),
  ('anime.delete', 'catalogue', 'Delete anime'),
  ('anime.publish', 'catalogue', 'Publish anime'),
  ('anime.unpublish', 'catalogue', 'Unpublish anime'),
  ('anime.merge', 'catalogue', 'Merge anime'),
  ('anime.feature', 'catalogue', 'Feature anime'),
  ('anime.import', 'catalogue', 'Import anime'),
  ('anime.export', 'catalogue', 'Export anime'),
  ('anime.bulk_edit', 'catalogue', 'Bulk edit anime'),
  ('anime.restore', 'catalogue', 'Restore anime'),
  ('episode.view', 'catalogue', 'View episode'),
  ('episode.create', 'catalogue', 'Create episode'),
  ('episode.edit', 'catalogue', 'Edit episode'),
  ('episode.delete', 'catalogue', 'Delete episode'),
  ('episode.publish', 'catalogue', 'Publish episode'),
  ('episode.import', 'catalogue', 'Import episode'),
  ('episode.bulk_edit', 'catalogue', 'Bulk edit episode'),
  ('character.view', 'catalogue', 'View character'),
  ('character.create', 'catalogue', 'Create character'),
  ('character.edit', 'catalogue', 'Edit character'),
  ('character.delete', 'catalogue', 'Delete character'),
  ('character.merge', 'catalogue', 'Merge character'),
  ('person.view', 'catalogue', 'View person'),
  ('person.create', 'catalogue', 'Create person'),
  ('person.edit', 'catalogue', 'Edit person'),
  ('person.delete', 'catalogue', 'Delete person'),
  ('person.merge', 'catalogue', 'Merge person'),
  ('staff.view', 'catalogue', 'View staff'),
  ('staff.edit', 'catalogue', 'Edit staff'),
  ('staff.assign', 'catalogue', 'Assign staff'),
  ('staff.delete', 'catalogue', 'Delete staff'),
  ('studio.view', 'catalogue', 'View studio'),
  ('studio.create', 'catalogue', 'Create studio'),
  ('studio.edit', 'catalogue', 'Edit studio'),
  ('studio.delete', 'catalogue', 'Delete studio'),
  ('studio.merge', 'catalogue', 'Merge studio'),
  ('genre.view', 'catalogue', 'View genre'),
  ('genre.create', 'catalogue', 'Create genre'),
  ('genre.edit', 'catalogue', 'Edit genre'),
  ('genre.delete', 'catalogue', 'Delete genre'),
  ('tag.view', 'catalogue', 'View tag'),
  ('tag.create', 'catalogue', 'Create tag'),
  ('tag.edit', 'catalogue', 'Edit tag'),
  ('tag.delete', 'catalogue', 'Delete tag'),
  ('tag.merge', 'catalogue', 'Merge tag'),
  ('mapping.view', 'catalogue', 'View mapping'),
  ('mapping.edit', 'catalogue', 'Edit mapping'),
  ('mapping.delete', 'catalogue', 'Delete mapping'),
  ('mapping.verify', 'catalogue', 'Verify mapping'),
  ('image.view', 'catalogue', 'View image'),
  ('image.upload', 'catalogue', 'Upload image'),
  ('image.edit', 'catalogue', 'Edit image'),
  ('image.delete', 'catalogue', 'Delete image'),
  ('image.set_primary', 'catalogue', 'Set primary image'),
  ('video.view', 'catalogue', 'View video'),
  ('video.add', 'catalogue', 'Add video'),
  ('video.edit', 'catalogue', 'Edit video'),
  ('video.delete', 'catalogue', 'Delete video'),
  ('relation.view', 'catalogue', 'View relation'),
  ('relation.create', 'catalogue', 'Create relation'),
  ('relation.delete', 'catalogue', 'Delete relation'),
  ('recommendation.view', 'catalogue', 'View recommendation'),
  ('recommendation.create', 'catalogue', 'Create recommendation'),
  ('recommendation.delete', 'catalogue', 'Delete recommendation'),
  ('synonym.view', 'catalogue', 'View synonym'),
  ('synonym.create', 'catalogue', 'Create synonym'),
  ('synonym.delete', 'catalogue', 'Delete synonym'),
  ('title.view', 'catalogue', 'View title'),
  ('title.edit', 'catalogue', 'Edit title'),
  ('franchise.view', 'catalogue', 'View franchise'),
  ('franchise.create', 'catalogue', 'Create franchise'),
  ('franchise.edit', 'catalogue', 'Edit franchise'),
  ('franchise.delete', 'catalogue', 'Delete franchise'),
  ('video_source.view', 'streaming', 'View video source'),
  ('video_source.create', 'streaming', 'Create video source'),
  ('video_source.edit', 'streaming', 'Edit video source'),
  ('video_source.delete', 'streaming', 'Delete video source'),
  ('video_source.verify', 'streaming', 'Verify video source'),
  ('video_source.report', 'streaming', 'Report video source'),
  ('source_mirror.view', 'streaming', 'View source mirror'),
  ('source_mirror.create', 'streaming', 'Create source mirror'),
  ('source_mirror.edit', 'streaming', 'Edit source mirror'),
  ('source_mirror.delete', 'streaming', 'Delete source mirror'),
  ('audio_track.view', 'streaming', 'View audio track'),
  ('audio_track.create', 'streaming', 'Create audio track'),
  ('audio_track.edit', 'streaming', 'Edit audio track'),
  ('audio_track.delete', 'streaming', 'Delete audio track'),
  ('subtitle_track.view', 'streaming', 'View subtitle track'),
  ('subtitle_track.create', 'streaming', 'Create subtitle track'),
  ('subtitle_track.edit', 'streaming', 'Edit subtitle track'),
  ('subtitle_track.delete', 'streaming', 'Delete subtitle track'),
  ('skip_segment.view', 'streaming', 'View skip segment'),
  ('skip_segment.create', 'streaming', 'Create skip segment'),
  ('skip_segment.edit', 'streaming', 'Edit skip segment'),
  ('skip_segment.delete', 'streaming', 'Delete skip segment'),
  ('skip_segment.vote', 'streaming', 'Vote skip segment'),
  ('user.view', 'users', 'View user'),
  ('user.list', 'users', 'List user'),
  ('user.create', 'users', 'Create user'),
  ('user.edit', 'users', 'Edit user'),
  ('user.delete', 'users', 'Delete user'),
  ('user.suspend', 'users', 'Suspend user'),
  ('user.ban', 'users', 'Ban user'),
  ('user.restore', 'users', 'Restore user'),
  ('user.impersonate', 'users', 'Impersonate user'),
  ('user.export', 'users', 'Export user'),
  ('user.reset_password', 'users', 'Reset password user'),
  ('user.verify_email', 'users', 'Verify email user'),
  ('profile.view', 'users', 'View profile'),
  ('profile.edit', 'users', 'Edit profile'),
  ('profile.delete', 'users', 'Delete profile'),
  ('profile.transfer', 'users', 'Transfer profile'),
  ('session.view', 'users', 'View session'),
  ('session.revoke', 'users', 'Revoke session'),
  ('device.view', 'users', 'View device'),
  ('device.revoke', 'users', 'Revoke device'),
  ('api_key.view', 'users', 'View api key'),
  ('api_key.create', 'users', 'Create api key'),
  ('api_key.revoke', 'users', 'Revoke api key'),
  ('oauth_app.view', 'users', 'View oauth app'),
  ('oauth_app.create', 'users', 'Create oauth app'),
  ('oauth_app.edit', 'users', 'Edit oauth app'),
  ('oauth_app.delete', 'users', 'Delete oauth app'),
  ('oauth_app.approve', 'users', 'Approve oauth app'),
  ('comment.view', 'community', 'View comment'),
  ('comment.create', 'community', 'Create comment'),
  ('comment.edit', 'community', 'Edit comment'),
  ('comment.delete', 'community', 'Delete comment'),
  ('comment.pin', 'community', 'Pin comment'),
  ('comment.hide', 'community', 'Hide comment'),
  ('comment.moderate', 'community', 'Moderate comment'),
  ('review.view', 'community', 'View review'),
  ('review.create', 'community', 'Create review'),
  ('review.edit', 'community', 'Edit review'),
  ('review.delete', 'community', 'Delete review'),
  ('review.feature', 'community', 'Feature review'),
  ('review.moderate', 'community', 'Moderate review'),
  ('review.hide', 'community', 'Hide review'),
  ('review_vote.view', 'community', 'View review vote'),
  ('review_vote.delete', 'community', 'Delete review vote'),
  ('forum.view', 'community', 'View forum'),
  ('forum.create', 'community', 'Create forum'),
  ('forum.edit', 'community', 'Edit forum'),
  ('forum.delete', 'community', 'Delete forum'),
  ('forum.lock', 'community', 'Lock forum'),
  ('forum.moderate', 'community', 'Moderate forum'),
  ('topic.view', 'community', 'View topic'),
  ('topic.create', 'community', 'Create topic'),
  ('topic.edit', 'community', 'Edit topic'),
  ('topic.delete', 'community', 'Delete topic'),
  ('topic.pin', 'community', 'Pin topic'),
  ('topic.lock', 'community', 'Lock topic'),
  ('topic.move', 'community', 'Move topic'),
  ('post.view', 'community', 'View post'),
  ('post.create', 'community', 'Create post'),
  ('post.edit', 'community', 'Edit post'),
  ('post.delete', 'community', 'Delete post'),
  ('post.hide', 'community', 'Hide post'),
  ('club.view', 'community', 'View club'),
  ('club.create', 'community', 'Create club'),
  ('club.edit', 'community', 'Edit club'),
  ('club.delete', 'community', 'Delete club'),
  ('club.manage', 'community', 'Manage club'),
  ('club.feature', 'community', 'Feature club'),
  ('club_member.view', 'community', 'View club member'),
  ('club_member.add', 'community', 'Add club member'),
  ('club_member.remove', 'community', 'Remove club member'),
  ('club_member.promote', 'community', 'Promote club member'),
  ('follow.view', 'community', 'View follow'),
  ('follow.remove', 'community', 'Remove follow'),
  ('friendship.view', 'community', 'View friendship'),
  ('friendship.remove', 'community', 'Remove friendship'),
  ('message.view', 'community', 'View message'),
  ('message.delete', 'community', 'Delete message'),
  ('message.moderate', 'community', 'Moderate message'),
  ('chat.view', 'community', 'View chat'),
  ('chat.moderate', 'community', 'Moderate chat'),
  ('library_entry.view', 'library', 'View library entry'),
  ('library_entry.create', 'library', 'Create library entry'),
  ('library_entry.edit', 'library', 'Edit library entry'),
  ('library_entry.delete', 'library', 'Delete library entry'),
  ('library_entry.export', 'library', 'Export library entry'),
  ('custom_list.view', 'library', 'View custom list'),
  ('custom_list.create', 'library', 'Create custom list'),
  ('custom_list.edit', 'library', 'Edit custom list'),
  ('custom_list.delete', 'library', 'Delete custom list'),
  ('custom_list.share', 'library', 'Share custom list'),
  ('custom_list.feature', 'library', 'Feature custom list'),
  ('collection.view', 'library', 'View collection'),
  ('collection.create', 'library', 'Create collection'),
  ('collection.edit', 'library', 'Edit collection'),
  ('collection.delete', 'library', 'Delete collection'),
  ('collection.share', 'library', 'Share collection'),
  ('bookmark.view', 'library', 'View bookmark'),
  ('bookmark.create', 'library', 'Create bookmark'),
  ('bookmark.delete', 'library', 'Delete bookmark'),
  ('favorite.view', 'library', 'View favorite'),
  ('favorite.create', 'library', 'Create favorite'),
  ('favorite.delete', 'library', 'Delete favorite'),
  ('watch_progress.view', 'library', 'View watch progress'),
  ('watch_progress.edit', 'library', 'Edit watch progress'),
  ('watch_progress.reset', 'library', 'Reset watch progress'),
  ('watch_history.view', 'library', 'View watch history'),
  ('watch_history.delete', 'library', 'Delete watch history'),
  ('watch_history.export', 'library', 'Export watch history'),
  ('report.view', 'moderation', 'View report'),
  ('report.resolve', 'moderation', 'Resolve report'),
  ('report.dismiss', 'moderation', 'Dismiss report'),
  ('report.escalate', 'moderation', 'Escalate report'),
  ('report.assign', 'moderation', 'Assign report'),
  ('appeal.view', 'moderation', 'View appeal'),
  ('appeal.review', 'moderation', 'Review appeal'),
  ('appeal.approve', 'moderation', 'Approve appeal'),
  ('appeal.reject', 'moderation', 'Reject appeal'),
  ('moderation_action.view', 'moderation', 'View moderation action'),
  ('moderation_action.create', 'moderation', 'Create moderation action'),
  ('moderation_action.revoke', 'moderation', 'Revoke moderation action'),
  ('spam_queue.view', 'moderation', 'View spam queue'),
  ('spam_queue.review', 'moderation', 'Review spam queue'),
  ('spam_queue.purge', 'moderation', 'Purge spam queue'),
  ('warning.view', 'moderation', 'View warning'),
  ('warning.issue', 'moderation', 'Issue warning'),
  ('warning.revoke', 'moderation', 'Revoke warning'),
  ('mute.view', 'moderation', 'View mute'),
  ('mute.issue', 'moderation', 'Issue mute'),
  ('mute.revoke', 'moderation', 'Revoke mute'),
  ('suspension.view', 'moderation', 'View suspension'),
  ('suspension.issue', 'moderation', 'Issue suspension'),
  ('suspension.revoke', 'moderation', 'Revoke suspension'),
  ('ban.view', 'moderation', 'View ban'),
  ('ban.issue', 'moderation', 'Issue ban'),
  ('ban.revoke', 'moderation', 'Revoke ban'),
  ('audit_log.view', 'moderation', 'View audit log'),
  ('audit_log.export', 'moderation', 'Export audit log'),
  ('security_log.view', 'moderation', 'View security log'),
  ('security_log.export', 'moderation', 'Export security log'),
  ('extension.view', 'developer', 'View extension'),
  ('extension.create', 'developer', 'Create extension'),
  ('extension.edit', 'developer', 'Edit extension'),
  ('extension.delete', 'developer', 'Delete extension'),
  ('extension.publish', 'developer', 'Publish extension'),
  ('extension.feature', 'developer', 'Feature extension'),
  ('extension.disable', 'developer', 'Disable extension'),
  ('extension_version.view', 'developer', 'View extension version'),
  ('extension_version.submit', 'developer', 'Submit extension version'),
  ('extension_version.edit', 'developer', 'Edit extension version'),
  ('extension_version.delete', 'developer', 'Delete extension version'),
  ('extension_version.publish', 'developer', 'Publish extension version'),
  ('extension_version.rollback', 'developer', 'Rollback extension version'),
  ('extension_review.view', 'developer', 'View extension review'),
  ('extension_review.approve', 'developer', 'Approve extension review'),
  ('extension_review.reject', 'developer', 'Reject extension review'),
  ('extension_review.flag', 'developer', 'Flag extension review'),
  ('extension_review.comment', 'developer', 'Comment extension review'),
  ('extension_install.view', 'developer', 'View extension install'),
  ('extension_install.install', 'developer', 'Install extension install'),
  ('extension_install.uninstall', 'developer', 'Uninstall extension install'),
  ('extension_install.force_update', 'developer', 'Force update extension install'),
  ('developer_account.view', 'developer', 'View developer account'),
  ('developer_account.apply', 'developer', 'Apply developer account'),
  ('developer_account.approve', 'developer', 'Approve developer account'),
  ('developer_account.revoke', 'developer', 'Revoke developer account'),
  ('marketplace_listing.view', 'developer', 'View marketplace listing'),
  ('marketplace_listing.create', 'developer', 'Create marketplace listing'),
  ('marketplace_listing.edit', 'developer', 'Edit marketplace listing'),
  ('marketplace_listing.delete', 'developer', 'Delete marketplace listing'),
  ('marketplace_listing.feature', 'developer', 'Feature marketplace listing'),
  ('marketplace_listing.set_price', 'developer', 'Set price marketplace listing'),
  ('achievement.view', 'gamification', 'View achievement'),
  ('achievement.create', 'gamification', 'Create achievement'),
  ('achievement.edit', 'gamification', 'Edit achievement'),
  ('achievement.delete', 'gamification', 'Delete achievement'),
  ('achievement.grant', 'gamification', 'Grant achievement'),
  ('achievement.revoke', 'gamification', 'Revoke achievement'),
  ('badge.view', 'gamification', 'View badge'),
  ('badge.create', 'gamification', 'Create badge'),
  ('badge.edit', 'gamification', 'Edit badge'),
  ('badge.delete', 'gamification', 'Delete badge'),
  ('badge.grant', 'gamification', 'Grant badge'),
  ('badge.revoke', 'gamification', 'Revoke badge'),
  ('xp.view', 'gamification', 'View xp'),
  ('xp.grant', 'gamification', 'Grant xp'),
  ('xp.revoke', 'gamification', 'Revoke xp'),
  ('xp.recalculate', 'gamification', 'Recalculate xp'),
  ('profile_stats.view', 'gamification', 'View profile stats'),
  ('profile_stats.recalculate', 'gamification', 'Recalculate profile stats'),
  ('leaderboard.view', 'gamification', 'View leaderboard'),
  ('leaderboard.configure', 'gamification', 'Configure leaderboard'),
  ('analytics.view', 'analytics', 'View analytics'),
  ('analytics.export', 'analytics', 'Export analytics'),
  ('analytics.configure', 'analytics', 'Configure analytics'),
  ('page_view.view', 'analytics', 'View page view'),
  ('page_view.export', 'analytics', 'Export page view'),
  ('page_view.purge', 'analytics', 'Purge page view'),
  ('search_stat.view', 'analytics', 'View search stat'),
  ('search_stat.export', 'analytics', 'Export search stat'),
  ('search_stat.purge', 'analytics', 'Purge search stat'),
  ('performance_metric.view', 'analytics', 'View performance metric'),
  ('performance_metric.export', 'analytics', 'Export performance metric'),
  ('performance_metric.purge', 'analytics', 'Purge performance metric'),
  ('error_log.view', 'analytics', 'View error log'),
  ('error_log.export', 'analytics', 'Export error log'),
  ('error_log.purge', 'analytics', 'Purge error log'),
  ('error_log.resolve', 'analytics', 'Resolve error log'),
  ('error_group.view', 'analytics', 'View error group'),
  ('error_group.resolve', 'analytics', 'Resolve error group'),
  ('error_group.ignore', 'analytics', 'Ignore error group'),
  ('stats_daily.view', 'analytics', 'View stats daily'),
  ('stats_daily.recompute', 'analytics', 'Recompute stats daily'),
  ('trending.view', 'analytics', 'View trending'),
  ('trending.recompute', 'analytics', 'Recompute trending'),
  ('setting.view', 'system', 'View setting'),
  ('setting.edit', 'system', 'Edit setting'),
  ('feature_flag.view', 'system', 'View feature flag'),
  ('feature_flag.edit', 'system', 'Edit feature flag'),
  ('feature_flag.create', 'system', 'Create feature flag'),
  ('feature_flag.delete', 'system', 'Delete feature flag'),
  ('webhook.view', 'system', 'View webhook'),
  ('webhook.create', 'system', 'Create webhook'),
  ('webhook.edit', 'system', 'Edit webhook'),
  ('webhook.delete', 'system', 'Delete webhook'),
  ('webhook.test', 'system', 'Test webhook'),
  ('job.view', 'system', 'View job'),
  ('job.retry', 'system', 'Retry job'),
  ('job.cancel', 'system', 'Cancel job'),
  ('job.purge', 'system', 'Purge job'),
  ('migration.view', 'system', 'View migration'),
  ('migration.run', 'system', 'Run migration'),
  ('cache.view', 'system', 'View cache'),
  ('cache.purge', 'system', 'Purge cache'),
  ('notification.view', 'system', 'View notification'),
  ('notification.send', 'system', 'Send notification'),
  ('notification.delete', 'system', 'Delete notification'),
  ('role.view', 'system', 'View role'),
  ('role.create', 'system', 'Create role'),
  ('role.edit', 'system', 'Edit role'),
  ('role.delete', 'system', 'Delete role'),
  ('role.assign', 'system', 'Assign role'),
  ('permission.view', 'system', 'View permission'),
  ('permission.grant', 'system', 'Grant permission'),
  ('permission.revoke', 'system', 'Revoke permission'),
  ('backup.view', 'system', 'View backup'),
  ('backup.create', 'system', 'Create backup'),
  ('backup.restore', 'system', 'Restore backup'),
  ('backup.download', 'system', 'Download backup'),
  ('ai_model.view', 'ai', 'View ai model'),
  ('ai_model.configure', 'ai', 'Configure ai model'),
  ('ai_model.deploy', 'ai', 'Deploy ai model'),
  ('ai_model.disable', 'ai', 'Disable ai model'),
  ('ai_recommendation.view', 'ai', 'View ai recommendation'),
  ('ai_recommendation.configure', 'ai', 'Configure ai recommendation'),
  ('ai_recommendation.run', 'ai', 'Run ai recommendation'),
  ('ai_moderation.view', 'ai', 'View ai moderation'),
  ('ai_moderation.configure', 'ai', 'Configure ai moderation'),
  ('ai_moderation.run', 'ai', 'Run ai moderation'),
  ('ai_moderation.review', 'ai', 'Review ai moderation'),
  ('ai_dataset.view', 'ai', 'View ai dataset'),
  ('ai_dataset.create', 'ai', 'Create ai dataset'),
  ('ai_dataset.edit', 'ai', 'Edit ai dataset'),
  ('ai_dataset.delete', 'ai', 'Delete ai dataset'),
  ('ai_dataset.export', 'ai', 'Export ai dataset')
ON CONFLICT (slug) DO NOTHING;

-- admin gets the entire catalogue
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p WHERE r.slug = 'admin'
ON CONFLICT DO NOTHING;

-- moderator: whole groups 'moderation', 'community'
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.slug = 'moderator' AND p."group" IN ('moderation', 'community')
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.slug = 'moderator' AND p.slug IN ('user.view', 'user.list', 'user.suspend', 'user.ban', 'user.restore', 'user.export', 'session.view', 'session.revoke', 'profile.view')
ON CONFLICT DO NOTHING;

-- developer: whole groups 'developer'
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.slug = 'developer' AND p."group" IN ('developer')
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.slug = 'developer' AND p.slug IN ('api_key.view', 'api_key.create', 'api_key.revoke', 'oauth_app.view', 'oauth_app.create', 'oauth_app.edit', 'oauth_app.delete')
ON CONFLICT DO NOTHING;

-- editor: whole groups 'catalogue', 'streaming'
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.slug = 'editor' AND p."group" IN ('catalogue', 'streaming')
ON CONFLICT DO NOTHING;

-- analyst: whole groups 'analytics'
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.slug = 'analyst' AND p."group" IN ('analytics')
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.slug = 'analyst' AND p.slug IN ('stats_daily.view', 'stats_daily.recompute', 'trending.view')
ON CONFLICT DO NOTHING;

