// /v1/announcements — one message, written by hand, shown to everybody.
//
// Not the notifications module. That one is per person and generated by things
// that happen; this is a single message an operator writes and everyone reads,
// with a window of time instead of a recipient. The two look alike for about a
// sentence and then stop.
//
// What the read returns depends on who is asking: `audience = 'everyone'` is
// the widest, a member also sees `'members'`, and somebody holding the
// permission also sees `'staff'`. The filter is in SQL rather than applied
// after, so a staff message never leaves the database on a request that should
// not have it.
//
// On an instance with `require_login` on — which this one has — an anonymous
// request never reaches here at all: the global gate in app.ts refuses it, and
// this route is deliberately **not** on that gate's exempt list. Opening it
// would widen the private surface for the sake of a message, and the three
// paths that are exempt are exempt because they are what a signed-out caller
// needs in order to stop being signed out. An announcement is not that.
//
// `'everyone'` still means what it says: it is the audience that will reach
// signed-out visitors if the instance is ever made public, and the semantics
// should be right before that day rather than after it.
//
// Writing is behind `announcement.manage`.

import { loadPermissions } from '../../middleware/auth.ts'
import { query, queryOne } from '../../infrastructure/database/index.ts'

import type { FastifyPluginAsync } from 'fastify'

const AUDIENCES = ['everyone', 'members', 'staff'] as const

const COLUMNS = `a.id, a.title, a.body, a.link_url, a.link_label, a.audience,
                 a.starts_at, a.ends_at, a.created_at`

/** The audiences this request may see, narrowest first. */
function visibleTo (signedIn: boolean, staff: boolean): string[] {
  const list = ['everyone']
  if (signedIn) list.push('members')
  if (staff) list.push('staff')
  return list
}

const routes: FastifyPluginAsync = async fastify => {
  /**
   * What is live for this viewer, newest first.
   *
   * `dismissed` is resolved here rather than left to the client: the client
   * would have to ask twice and could still show a message somebody closed on
   * another device. A signed-out viewer has no profile and dismisses nothing —
   * for them the client remembers locally, which is the most a browser with no
   * account can honestly do.
   */
  fastify.get('/', async request => {
    const profileId = (request.headers['x-profile-id'] as string | undefined) ?? null
    const signedIn = Boolean(request.user?.sub)
    const staff = signedIn && (await loadPermissions(request.user.sub)).has('announcement.manage')

    const data = await query(
      `SELECT ${COLUMNS},
              CASE WHEN $2::uuid IS NULL THEN false
                   ELSE EXISTS (SELECT 1 FROM announcement_dismissals d
                                 WHERE d.announcement_id = a.id AND d.profile_id = $2::uuid)
              END AS dismissed
         FROM announcements a
        WHERE a.audience = ANY($1::text[])
          AND a.starts_at <= now()
          AND (a.ends_at IS NULL OR a.ends_at > now())
        ORDER BY a.starts_at DESC
        LIMIT 20`,
      [visibleTo(signedIn, staff), profileId]
    )
    return { data }
  })

  /** Close one for this profile. Idempotent: closing twice is not an error. */
  fastify.post('/:id/dismiss', {
    onRequest: fastify.authenticate,
    schema: { params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } } }
  }, async (request, reply) => {
    const { id } = request.params as { id: string }
    const profileId = request.headers['x-profile-id'] as string | undefined
    if (!profileId) return await reply.code(400).send({ code: 'YUME-ANN-400', title: 'Missing X-Profile-Id header' })

    await query(
      `INSERT INTO announcement_dismissals (announcement_id, profile_id) VALUES ($1, $2)
       ON CONFLICT DO NOTHING`,
      [id, profileId]
    )
    return await reply.code(204).send()
  })

  // ---- authoring -----------------------------------------------------------

  /** Everything, live or not, for the people who write them. */
  fastify.get('/all', { onRequest: fastify.requirePermission('announcement.manage') }, async () => ({
    data: await query(`SELECT ${COLUMNS} FROM announcements a ORDER BY a.starts_at DESC LIMIT 200`)
  }))

  const bodySchema = {
    type: 'object',
    required: ['title', 'body'],
    properties: {
      title: { type: 'string', minLength: 1, maxLength: 200 },
      body: { type: 'string', minLength: 1, maxLength: 8000 },
      linkUrl: { type: ['string', 'null'], maxLength: 2000 },
      linkLabel: { type: ['string', 'null'], maxLength: 60 },
      audience: { enum: [...AUDIENCES] },
      startsAt: { type: ['string', 'null'], format: 'date-time' },
      endsAt: { type: ['string', 'null'], format: 'date-time' }
    },
    additionalProperties: false
  } as const

  fastify.post('/', {
    onRequest: fastify.requirePermission('announcement.manage'),
    schema: { body: bodySchema }
  }, async (request, reply) => {
    const b = request.body as Record<string, unknown>
    const row = await queryOne(
      `INSERT INTO announcements (title, body, link_url, link_label, audience, starts_at, ends_at, created_by)
       VALUES ($1, $2, $3, $4, COALESCE($5, 'members'), COALESCE($6::timestamptz, now()), $7::timestamptz, $8)
       RETURNING id`,
      [b.title, b.body, b.linkUrl ?? null, b.linkLabel ?? null, b.audience ?? null,
        b.startsAt ?? null, b.endsAt ?? null, request.user.sub]
    )
    return await reply.code(201).send(row)
  })

  fastify.patch('/:id', {
    onRequest: fastify.requirePermission('announcement.manage'),
    schema: {
      params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } },
      body: { ...bodySchema, required: [] }
    }
  }, async (request, reply) => {
    const { id } = request.params as { id: string }
    const b = request.body as Record<string, unknown>
    // COALESCE per column, so a PATCH naming one field leaves the rest alone.
    const row = await queryOne(
      `UPDATE announcements
          SET title = COALESCE($2, title), body = COALESCE($3, body),
              link_url = COALESCE($4, link_url), link_label = COALESCE($5, link_label),
              audience = COALESCE($6, audience),
              starts_at = COALESCE($7::timestamptz, starts_at),
              ends_at = COALESCE($8::timestamptz, ends_at),
              updated_at = now()
        WHERE id = $1
        RETURNING id`,
      [id, b.title ?? null, b.body ?? null, b.linkUrl ?? null, b.linkLabel ?? null,
        b.audience ?? null, b.startsAt ?? null, b.endsAt ?? null]
    )
    if (!row) return await reply.code(404).send({ code: 'YUME-ANN-404', title: 'Not Found' })
    return row
  })

  fastify.delete('/:id', {
    onRequest: fastify.requirePermission('announcement.manage'),
    schema: { params: { type: 'object', properties: { id: { type: 'string', format: 'uuid' } } } }
  }, async (request, reply) => {
    const { id } = request.params as { id: string }
    await query('DELETE FROM announcements WHERE id = $1', [id])
    return await reply.code(204).send()
  })
}

export default routes
