-- ============================================================================
-- 0041 — announcements, and a visibility flag on the development log
-- ============================================================================
-- Two things the owner asked for, and they share a shape: something written by
-- a person with a permission, shown to everybody else, and with an explicit
-- say over whether it is shown at all.
--
-- ---- announcements ---------------------------------------------------------
-- A way to tell everybody something once: a new domain, a planned outage, a
-- feature worth finding. Not the notifications table, which is per person and
-- generated by events — this is one message written by hand and read by
-- everyone, and it needs a window of time, not a recipient.
--
-- `starts_at` / `ends_at` rather than a boolean, because the useful case is
-- "show this for the next fortnight" and a boolean makes that a reminder to
-- come back and turn it off. NULL at either end means open-ended.
--
-- `audience` decides who sees it, because some announcements are for the
-- people who can act on them: 'everyone' includes signed-out visitors,
-- 'members' is anybody signed in, 'staff' is anybody holding a permission.
--
-- ---- release visibility ----------------------------------------------------
-- The development log has been database-driven since 0036, with ten releases
-- in it, but every row it holds is public the moment it exists. The request was
-- to write everything down and publish only part of it — internal notes,
-- security work whose detail should land after the fix is out, entries drafted
-- before they are ready.
--
-- `is_public` defaults to TRUE so the ten existing releases keep behaving
-- exactly as they do today; only a row explicitly marked private disappears
-- from the public read.
--
-- `category` is the chip the reference shows above each release. Free text
-- rather than an enum: the set of areas a project talks about is not something
-- to freeze in a constraint.
--
-- Backwards compatible in both directions. An older binary does not know the
-- new columns and never selects them; the defaults mean it also cannot write a
-- row that the new code would hide by accident.
-- ============================================================================

CREATE TABLE IF NOT EXISTS announcements (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title       text NOT NULL CHECK (length(title) BETWEEN 1 AND 200),
  body        text NOT NULL CHECK (length(body) BETWEEN 1 AND 8000),
  -- Optional call to action. Both or neither: a label with no link is a dead
  -- button, and a link with no label has nothing to put on it.
  link_url    text CHECK (link_url IS NULL OR link_url ~ '^https?://'),
  link_label  text CHECK (link_label IS NULL OR length(link_label) BETWEEN 1 AND 60),
  audience    text NOT NULL DEFAULT 'members' CHECK (audience IN ('everyone', 'members', 'staff')),
  starts_at   timestamptz NOT NULL DEFAULT now(),
  ends_at     timestamptz,
  created_by  uuid REFERENCES users(id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT announcements_link_pair CHECK ((link_url IS NULL) = (link_label IS NULL)),
  CONSTRAINT announcements_window CHECK (ends_at IS NULL OR ends_at > starts_at)
);

COMMENT ON TABLE announcements IS
  'Hand-written messages shown to everyone for a window of time. Per-person, event-driven messages are the notifications table.';

-- The read is always "what is live right now". The predicate cannot say that —
-- now() is not IMMUTABLE, so Postgres refuses it in an index predicate — so the
-- window columns are indexed and the comparison happens at query time. The
-- table is small enough that this costs nothing.
CREATE INDEX IF NOT EXISTS announcements_window_idx
  ON announcements (starts_at DESC, ends_at);

-- Dismissal is per profile, not per account: two people sharing an account
-- should not dismiss each other's news.
CREATE TABLE IF NOT EXISTS announcement_dismissals (
  announcement_id uuid NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  profile_id      uuid NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  dismissed_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (announcement_id, profile_id)
);

COMMENT ON TABLE announcement_dismissals IS
  'Which profile has closed which announcement. Per profile so shared accounts do not dismiss for each other.';

-- ---- the permission --------------------------------------------------------

INSERT INTO permissions (slug, description, "group", status)
VALUES ('announcement.manage', 'Write and publish site-wide announcements', 'admin', 'active')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
 WHERE r.slug = 'admin' AND p.slug = 'announcement.manage'
ON CONFLICT DO NOTHING;

-- ---- development log visibility -------------------------------------------

ALTER TABLE releases ADD COLUMN IF NOT EXISTS is_public boolean NOT NULL DEFAULT true;
ALTER TABLE releases ADD COLUMN IF NOT EXISTS category text CHECK (category IS NULL OR length(category) BETWEEN 1 AND 40);

COMMENT ON COLUMN releases.is_public IS
  'False keeps the release out of the public log while still recording it. Defaults true so existing rows are unchanged.';
COMMENT ON COLUMN releases.category IS
  'The chip shown above a release, e.g. "Weboldal" or "Lejátszó". Free text on purpose.';

CREATE INDEX IF NOT EXISTS releases_public_idx ON releases ("position" DESC, released_on DESC) WHERE is_public;
